### ISSUE TITLE
Unable to commit changes when renaming directory

### ISSUE THREAD

**Issue by jose-ochoa** [Medology/submodules#30]
# Story
**As a dev of a git repository**, I need to be able to commit changes.

## Steps to Recreate  
![image](https://user-images.githubusercontent.com/16085034/92732116-97958500-f33b-11ea-8fe6-1718fdff585b.png)

## Expected Behavior  
Should commit changes successfully when simply rename a directory.

## Actual Behavior
Fails to commit changes

## Business Value
This should be fixed as it slows down or the ability to make codebase changes.

## Notes
I renamed an entire directory, renaming a file should also be checked, along with renaming a file and making modifications to it. 

I used the `git mv` command to rename.

# Acceptance Criteria
- [ ] Expected Behavior is exhibited when steps to recreate are followed

# Subject Domain Experts
- Brandon

# Proposed Solution  
n/a

# Progress
### Ready for Ready to Work
- [ ] The Issue maintains standard format for Issues and meets INVEST
- [ ] Story and Business Value complete
- [ ] Steps to Recreate, Expected Behavior, and Actual Behavior complete
- [ ] The person who will Approve story identified
- [ ] Dependencies Identified

### Ready for Review
- [ ] ~Proposed solution defined and accepted by Approver~
- [ ] ~Code implemented and built~
- [ ] ~Testing implemented and passed~

### Ready for Pre-Production QA
- [ ] Peer Reviews complete with all changes tested
- [ ] Special testing instructions noted
- [ ] Acceptance Test cases created and reviewed by QA
- [ ] System is behaving in accordance with "Expected Behavior"
- [ ] Issue scored

### Ready for Deploy and Test
- [ ] PreProduction QA Test Passed
- [ ] New production environmental variables added (if applicable)
 
### Ready for Production QA
- [ ] Software deployed in production with no errors

### Ready for SM Approval
- [ ] Production QA Test Passed
- [ ] Manual Acceptance Test Results included in Comment

### Ready for PO Approval
- [ ] Issue complete and correct in all required sections
- [ ] All checkboxes checked

**Comment by BKorenek** [comment]
![image](https://user-images.githubusercontent.com/10714448/93591698-743f8b00-f976-11ea-96a0-cd431a106811.png)

**Comment by BKorenek** [comment]
Editing and renaming a file
![image](https://user-images.githubusercontent.com/10714448/93592382-b1584d00-f977-11ea-95b2-51b51eb2f5fc.png)

**Comment by BKorenek** [comment]
Confirmed with Jose this is corrected.

**Comment by Chekote** [comment]
Tested with the same scenario posted by José and it works as expected.
