### ISSUE TITLE
Discrepancy in CS fixer when running locally vs CI

### ISSUE THREAD

**Issue by jose-ochoa** [Medology/submodules#32]
# Story
**As a dev of iLab**, I need my code changes to run in CI.

## Steps to Recreate  

Commit creation:

![image](https://user-images.githubusercontent.com/16085034/94065017-27154c00-fdb0-11ea-9458-d267423d75a6.png)

When the branch is pushed to a PR:
![image](https://user-images.githubusercontent.com/16085034/94065144-54fa9080-fdb0-11ea-9d6a-9cedb654a899.png)

Link to failed build: https://app.circleci.com/pipelines/github/Medology/iLab/607/workflows/1029460b-981b-488d-acf6-49e96707655c/jobs/2283

PR: https://github.com/Medology/iLab/pull/708

## Expected Behavior  
pre-commit hook on local machine should result in the same outcome as in CI

## Actual Behavior
Locally allows me to commit changes without issue, in CI fails to run cs fixer on my changes.

## Business Value
Uh, being able to commit code.

## Notes
N/A

# Acceptance Criteria
- [x] Expected Behavior is exhibited when steps to recreate are followed

# Announcement Message
releasenotes: N/A

devchat: We can now commits all the codes

# Subject Domain Experts
Brandon

# Proposed Solution  
N/A

# Progress
### Ready for Planning
- [x] Story and Business Value complete
- [x] Initial Acceptance Criteria Defined
- [x] The person who will Approve story identified
- [x] Proposed Solution provided

### Ready for Review
- [x] Testing implemented and passed

### Ready for Pre-Production QA
- [x] Issue scored
- [x] Special testing instructions noted
- [x] Acceptance criteria met - boxes checked
- [x] Announcement message created

### Ready for SM Approval
- [x] Manual Acceptance Test Results included in Comment

### Ready for PO Approval
- [x] Issue complete and correct in all required sections
- [x] All checkboxes checked
- [x] Announcement message approved

**Comment by manuerumx** [comment]
I just picked this issue, but no clue about how the fixers works or their implementation, I just started to investigate how works. I don't expect to have a PR ready today.

**Comment by manuerumx** [comment]
Scored with @BKorenek and @rashidsaf

**Comment by manuerumx** [comment]
Approved by reviewers. I will ask for help to force-merge, due to a bug in the Pullapprove configuration for the submodules project (https://github.com/Medology/submodules/issues/34)

**Comment by manuerumx** [comment]
Merged and tested with the sample branch @jose-ochoa created.

![image.png](https://images.zenhubusercontent.com/5d0801d09943fc312156c8c4/708a6cd9-3ac9-40dd-bacb-23807ad6b9d5)

Moving to Production QA

**Comment by manuerumx** [comment]
Non-QA changes.

**Comment by kabbatehl** [comment]
### QA
Nothing to test.  Moving to Approval.
