### ISSUE TITLE
Pull approve wrong configuration

### ISSUE THREAD

**Issue by manuerumx** [Medology/submodules#34]
# Story
**As a Dev of STDcheck, Healthlabs, UTITreatmen**, I need reviewers to be assigned automatically in the pull requests.

## Steps to Recreate  
Create a PR in submodules repository

## Expected Behavior  
Reviewers should be assigned automatically.

## Actual Behavior
> pullapprove — Config is invalid

![image](https://user-images.githubusercontent.com/3312001/95086393-10db8a00-06e6-11eb-9e06-98b607283201.png)

Ex. https://github.com/Medology/submodules/pull/33

## Business Value
The time a developer takes to make changes is reduced

## Notes
N/A

## Acceptance Criteria
- [X] A valid PR should get reviewers assigned automatically.

## Announcement Message
releasenotes: N/A

devchat: Pullapprove works on Submodules

# Proposed Solution  
Fix the global configuration to assign reviewers in the submodules repository

## Subject Domain Experts
@BKorenek 

### Ready for Planning
- [ ] Story and Business Value complete
- [ ] Initial Acceptance Criteria Defined
- [ ] The person who will Approve story identified
- [ ] Proposed Solution provided

### Ready for Review
- [ ] Testing implemented and passed

### Ready for Pre-Production QA
- [ ] Issue scored
- [ ] Acceptance criteria met - boxes checked
- [ ] Announcement message created

### Ready for SM Approval
- [ ] Manual Acceptance Test Results included in Comment

### Ready for PO Approval
- [ ] Announcement message approved
- [ ] Issue complete and correct in all required sections
- [ ] All checkboxes checked

**Comment by fortoulrodolfo** [comment]
Updated PullApprove config. I will check with Donald if the config is right.

**Comment by fortoulrodolfo** [comment]
I need to score and move forward
