### ISSUE TITLE
Pin PHP-CS-Fixer version

### ISSUE THREAD

**Issue by manuerumx** [Medology/submodules#57]
# Story
**As a developer**, I need to be confident about the tools we use work as expected.

## Steps to Recreate  
Create a PR in any repository which uses submodules and update a PHP file

## Expected Behavior  
PHP-CS-Fixer must be executed and the file is optimized

## Actual Behavior
Locally is working since most developers already have a working version image. CI is failing at the step when the fixer is executed since the image is downloaded at the moment.

## Business Value
Developer can continue working taking advantage of the tool to have standardized code.

## Notes
< special notes or suggestions to the development team on any information pertinent to the bug. > 

## Acceptance Criteria
- [X] Image version is pinned

## Announcement Message
releasenotes: N/A

devchat: Submodules project is updated with a working version for the PHP-CS-Fixer image. All the repositories should be updated and any failing PR must be rebased as soon as the submodule project is updated in the repository.

# Proposed Solution  
Use the latest working version and change the tag for the image used to fix PHP files.

## Subject Matter Experts
Donald

**Comment by HLCharlie** [comment]
created this Issue; need to create an Issue to push the image instead of pulling

**Comment by manuerumx** [comment]
Follow up issue to push the docker image to GCR registry created. #62
